import requests

def check_status():
    r = requests.get("http://localhost:1234/statuscheck")
    print(r)

def check_predictions():
    r = requests.post("http://localhost:1234/predict", json={'instance': [{'RevolverStatus': 0, 
    'TermInMonths': 84, 
    'BorrBankSameState': 0, 
    'TotPctDefault': .19,
    'YearlyDefaultCounts': 100, 
    'YearlyPctDefault': .15,
    'subpgmdesc__Community Advantage Initiative': 0,
    'subpgmdesc__Community Express': 1, 
    'subpgmdesc__Contract Guaranty': 0,
    'subpgmdesc__Defense Loans and Technical Assistance, Funded 9/26/95': 0,
    'subpgmdesc__EXPORT IMPORT HARMONIZATION': 0,
    'subpgmdesc__FA$TRK (Small Loan Express)': 0, 
    'subpgmdesc__Guaranty': 0,
    'subpgmdesc__Gulf Opportunity': 0,
    'subpgmdesc__International Trade - Sec, 7(a) (16)': 0,
    'subpgmdesc__Lender Advantage Initiative': 0,
    'subpgmdesc__Patriot Express': 0,
    'subpgmdesc__Revolving Line of Credit Exports - Sec. 7(a) (14)': 0,
    'subpgmdesc__Rural Lender Advantage': 0,
    'subpgmdesc__Seasonal Line of Credit': 0, 
    'subpgmdesc__Small Asset Based': 0,
    'subpgmdesc__Small General Contractors - Sec. 7(a) (9)': 0,
    'subpgmdesc__Standard Asset Based': 0,
    'subpgmdesc__USCAIP Guaranty (NAFTA)': 0, 
    'subpgmdesc__Y2K Loan': 0,
    'NaicsCode__21': 0, 
    'NaicsCode__22': 0, 
    'NaicsCode__23': 0, 
    'NaicsCode__31': 0,
    'NaicsCode__32': 0, 
    'NaicsCode__33': 0, 
    'NaicsCode__42': 0, 
    'NaicsCode__44': 1,
    'NaicsCode__45': 0, 
    'NaicsCode__48': 0, 
    'NaicsCode__49': 0, 
    'NaicsCode__51': 0,
    'NaicsCode__52': 0, 
    'NaicsCode__53': 0, 
    'NaicsCode__54': 0, 
    'NaicsCode__55': 0,
    'NaicsCode__56': 0, 
    'NaicsCode__61': 0, 
    'NaicsCode__62': 0, 
    'NaicsCode__71': 0,
    'NaicsCode__72': 0, 
    'NaicsCode__81': 0, 
    'NaicsCode__92': 0,
    'ApprovalFiscalYear__2001': 0, 
    'ApprovalFiscalYear__2002': 0,
    'ApprovalFiscalYear__2003': 0, 
    'ApprovalFiscalYear__2004': 0,
    'ApprovalFiscalYear__2005': 0, 
    'ApprovalFiscalYear__2006': 0,
    'ApprovalFiscalYear__2007': 0, 
    'ApprovalFiscalYear__2008': 0,
    'ApprovalFiscalYear__2009': 0, 
    'ApprovalFiscalYear__2010': 0,
    'ApprovalFiscalYear__2011': 0, 
    'ApprovalFiscalYear__2012': 0,
    'ApprovalFiscalYear__2013': 0, 
    'ApprovalFiscalYear__2014': 0,
    'ApprovalFiscalYear__2015': 0, 
    'ApprovalFiscalYear__2016': 0,
    'ApprovalFiscalYear__2017': 0, 
    'ApprovalFiscalYear__2018': 0,
    'ApprovalFiscalYear__2019': 0, 
    'ApprovalFiscalYear__2020': 0,
    'ApprovalFiscalYear__2021': 0, 
    'ApprovalFiscalYear__2022': 1}]})
    print(r)

    prediction = r.content
    print(prediction.decode("utf-8"))
