version: 2.1

orbs:
  python: circleci/python@2.0.3

parameters:
  run-build-app:
    type: boolean
    default: true
  run-build-eda:
    type: boolean
    default: true
  run-build-sample:
    type: boolean
    default: true

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
          name: Test

workflows:
  service-1:
    when: << pipeline.parameters.run-build-app >>
    jobs:
      - build
      - run:
          command: make test_app
  service-2:
    when: << pipeline.parameters.run-build-eda >>
    jobs:
      - build
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
  service-3:
    when: << pipeline.parameters.run-build-sample >>
    jobs:
      - build
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest