version: 2.1

orbs:
  python: circleci/python@2.0.3

parameters:
  run-build-app:
    type: boolean
    default: true
  run-build-eda:
    type: boolean
    default: true
  run-build-sample:
    type: boolean
    default: true

jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

workflows:
  service-1:
    when: << pipeline.parameters.run-build-app >>
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
  service-2:
    when: << pipeline.parameters.run-build-eda >>
    jobs:
      - eda/test:
          build:
            docker:
              - image: cimg/python:3.9.5
            parallelism: 4
            resource_class: large
            working_directory: ~/sba-loan-credit-analysis
            steps:
              - run:
                  name: install eda dependencies
                  no_output_timeout: 30m
                  command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
              - run:
                  name: run eda tests
                  no_output_timeout: 30m
                  command: |
                    . venv/bin/activate
                    make test_eda
  service-3:
    when: << pipeline.parameters.run-build-sample >>
    jobs:
      - eda/test:
          build:
            docker:
              - image: cimg/python:3.9.5
            parallelism: 4
            resource_class: large
            working_directory: ~/sba-loan-credit-analysis
            steps:
              - run:
                  name: install sample dependencies
                  no_output_timeout: 30m
                  command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
              - run:
                  name: run sample tests
                  no_output_timeout: 30m
                  command: |
                    . venv/bin/activate
                    make test_sample