version: 2.1

orbs:
  python: circleci/python@1.5.0

parameters:
  run-build-app:
    type: boolean
    default: false
  run-build-eda:
    type: boolean
    default: false
  run-build-sample:
    type: boolean
    default: false

workflows:
  service-1:
    when: << pipeline.parameters.run-build-app >>
    jobs:
      - python/test:
          name: test-app
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            make test_app'
  service-2:
    when: << pipeline.parameters.run-build-eda >>
    jobs:
      - eda/test:
          build:
            docker:
              - image: cimg/python:3.9.5
            parallelism: 4
            resource_class: large
            working_directory: ~/sba-loan-credit-analysis
            steps:
              - run:
                  name: install eda dependencies
                  no_output_timeout: 30m
                  command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
              - run:
                  name: run eda tests
                  no_output_timeout: 30m
                  command: |
                    . venv/bin/activate
                    make test_eda
  service-3:
    when: << pipeline.parameters.run-build-sample >>
    jobs:
      - eda/test:
          build:
            docker:
              - image: cimg/python:3.9.5
            parallelism: 4
            resource_class: large
            working_directory: ~/sba-loan-credit-analysis
            steps:
              - run:
                  name: install sample dependencies
                  no_output_timeout: 30m
                  command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
              - run:
                  name: run sample tests
                  no_output_timeout: 30m
                  command: |
                    . venv/bin/activate
                    make test_sample