version: 2.1

orbs:
  python: circleci/python@2.0.3

parameters:
  run-build-app:
    type: boolean
    default: true
  run-build-eda:
    type: boolean
    default: true
  run-build-sample:
    type: boolean
    default: true

jobs:
  build-test-app:
    docker:
      - image: cimg/python:3.9.5
    parallelism: 4
    resource_class: large
    working_directory: ~/sba-loan-credit-analysis
    steps:
      - checkout
      - run:
          name: install dependencies
          no_output_timeout: 30m
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            make test_app

workflows:
  service-1:
    when: << pipeline.parameters.run-build-app >>
    jobs:
      - build-test-app

  service-2:
    when: << pipeline.parameters.run-build-eda >>
    jobs:
      - build
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
  service-3:
    when: << pipeline.parameters.run-build-sample >>
    jobs:
      - build
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest