version: 2.1

orbs:
  python: circleci/python@2.0.3

parameters:
  run-build-app:
    type: boolean
    default: true
  run-build-eda:
    type: boolean
    default: true
  run-build-sample:
    type: boolean
    default: true

jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

workflows:
  service-1:
    when: << pipeline.parameters.run-build-app >>
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
  service-2:
    when: << pipeline.parameters.run-build-eda >>
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
  service-3:
    when: << pipeline.parameters.run-build-sample >>
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest